### ISSUE TITLE
(Get Involved)

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#101]
The description under "Apply to be a Mentor"
have the "Beat the Odds!" on one line, it looks more aesthetic

**Comment by vikaspotluri123** [comment]
This is what it looks like now. Based on screen size, the text will wrap.
![image](https://cloud.githubusercontent.com/assets/4383564/23837869/fd19baf0-075c-11e7-8147-77952746c766.png)

**Comment by thelinkscholars** [comment]
That's okay
