### ISSUE TITLE
(Contact) Calendar section

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#103]
How do we update or change the calendar section? How does the Calendar work?

**Comment by vikaspotluri123** [comment]
_data/events.yml
- a hyphen denotes a new event
- Let me know if any of the names aren't self explanatory 
- Haven't thought much about the look and feel yet
- Might be better to have its own page; seems out of place in the contact us section.

**Comment by thelinkscholars** [comment]
I'm not sure if we need a dedicated page to our calendar, we'll see. And if I update event/calendar data do you want me to let you know here so that when you pull the data is not lost?

**Comment by thelinkscholars** [comment]
I updated the events.yml file just so you are aware

**Comment by vikaspotluri123** [comment]
Thanks for letting me know! I have updated my code.
