### ISSUE TITLE
Domain Registered!

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#107]
We've Registered as thelinkscholars.org 
Please let me know the next steps for carrying over the website to Google Domains :)

**Comment by vikaspotluri123** [comment]
Is it done via GoDaddy?

**Comment by thelinkscholars** [comment]
It is on Google Domains

**Comment by vikaspotluri123** [comment]
Are you free to call?

**Comment by thelinkscholars** [comment]
Yes I am
