### ISSUE TITLE
MOTM border frame

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#13]
Hey I found this super cute polaroid frame and I wanted to use this as a border for the MOTM section on our website homepage

**Comment by thelinkscholars** [comment]
![polaroid-1277003_1920.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58097f8fd894b10e00f3300f/125516c66e82c728ace21e0d46f89b9622908ca08ba4ee11f30aa0c47a79762a7b54e1673295f127b54778154d555ca9490d5f42f5fd8f2fa6bf3f238d5c0bef846a5e76c33e19bea4905dee5fee7fd616cfe3fe9846d2e9342fe68e8b493d180c1b81ff5f33a78b06.png)

**Comment by HexRdesign** [comment]
Feel free to use it! I think it would be better to photoshop the images together (make sure you upload both just in case!) because getting multiple images to align with each other on multiple screen sizes is extremely complicated!

**Comment by thelinkscholars** [comment]
Alright sounds good
