### ISSUE TITLE
Update main team title

### ISSUE THREAD

**Issue by HexRdesign** [thelinkscholars/thelinkscholars.github.io#2]
Updated title needs to be "Meet the Team!"
Team members are: (Maesha Shonar: Founder, Priyata Richy: Program Director, Ishaat Hossain: Marketing Director, Ahmed Hussain: Head of Outreach)

**Comment by HexRdesign** [comment]
@thelinkscholars Where is this?

**Comment by thelinkscholars** [comment]
The Team page
