### ISSUE TITLE
(Home) Zoom out cover picture

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#23]

**Comment by HexRdesign** [comment]
@thelinkscholars This is zoomed out as much as possible. The background area is rectangular and the picture is square. Would you like it shifted?

**Comment by thelinkscholars** [comment]
Yes

**Comment by HexRdesign** [comment]
@thelinkscholars  What direction should I move it? Up or down?

**Comment by thelinkscholars** [comment]
move it up, i'll see how it looks and move this into ready once you do. If it's okay, i'll comment here saying it's good or if it should be moved down or reverted back to original

**Comment by HexRdesign** [comment]
Sounds good! That's how it works

**Comment by HexRdesign** [comment]
Changes have been made

**Comment by thelinkscholars** [comment]
okay nevermind, we'll revert to original and keep it
