### ISSUE TITLE
(Home) decrease font size by 50%

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#24]
Decrease the font size of the title "Beating the Odds" by 50%

**Comment by HexRdesign** [comment]
@thelinkscholars Where does this need to be done? Most of the text is "flow-text", meaning it scales to fit the size of the screen

**Comment by thelinkscholars** [comment]
It's not possible to decrease the font size at all?

**Comment by HexRdesign** [comment]
It's advisable not to. The framework developers have taken into account the usability requirements of a wide array of devices and developed a specification to meet the standards. If still needed, I will manually override everything.

**Comment by thelinkscholars** [comment]
alright that's okay you don't have too, are you able to complete issue number 23?
