### ISSUE TITLE
Pages text on google docs

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#28]
You will find all the required and necessary text in the google doc. Each page is separated by a divider on the doc, just copy and paste the text and remove any symbols such as: <,>,-, etc.

**Comment by thelinkscholars** [comment]
please don't copy over anything that says:
"Please add text" or anything along those lines, leave those alone, my team is working on filling in those descriptions

**Comment by thelinkscholars** [comment]
if you feel there's not enough information then you don't have to copy it over, we'll keep updating that doc as we go on

**Comment by HexRdesign** [comment]
@thelinkscholars I'm thinking since most pages have sections to use something along the lines of the services page for quick navigation. What do you think?

**Comment by thelinkscholars** [comment]
yes, I like the idea, keep it
