### ISSUE TITLE
Add mentors to team page

### ISSUE THREAD

**Issue by HexRdesign** [thelinkscholars/thelinkscholars.github.io#3]
Needs to be done under main team section
the mentors will go under the main team following a divider to split the sections with the carousel effect but their title will be              "Meet Our Mentors!"

**Comment by HexRdesign** [comment]
@thelinkscholars Is this on the home page or the team page?

**Comment by thelinkscholars** [comment]
team page

**Comment by thelinkscholars** [comment]
team page
