### ISSUE TITLE
(Blog) add a featured on section on this page, we'll add the features soon

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#32]

**Comment by vikaspotluri123** [comment]
What do you mean by featured?

**Comment by thelinkscholars** [comment]
http://www.middyfund.com/in-the-news.html
this is an example. It's basically a page for us to show people where we've been mentioned

**Comment by vikaspotluri123** [comment]
Okay. I will create this as a press page. Here's an example: https://www.remind.com/press
Featured could also refer to posts in the blog that deserve / need more attention. 
Do you plan on writing a post for every feature, or just having an archive of places where you were featured?

**Comment by thelinkscholars** [comment]
we will do posts for every individual feature. Our facebook page has them so we will most likely just copy and paste over

**Comment by vikaspotluri123** [comment]
That makes it easy for me! Just add the tag `press` and they will show up in the press page.

**Comment by thelinkscholars** [comment]
Alright perfect!

**Comment by thelinkscholars** [comment]
#press
