### ISSUE TITLE
(About) make the blur for the cover picture 10%

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#33]

**Comment by vikaspotluri123** [comment]
Blurring w/ web development is done through pixels. There is not much documentation on it, so it's not easy to map a pixel to a percentage. Can you please let me know if more or less blur is needed?

**Comment by thelinkscholars** [comment]
less blur

**Comment by vikaspotluri123** [comment]
What do you think?
