### ISSUE TITLE
(Team) update mentors headshots

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#38]
Please be careful when using these pictures. Make sure they are centered correctly and the file name is the person name. Note: don't use any pictures that don't have a name

**Comment by vikaspotluri123** [comment]
I'm in the process of working on them now. I have subpar photo editing skills, but I will do my best.

**Comment by thelinkscholars** [comment]
much appreciated. please provide me with the proper dimensions so that further pictures that are uploaded can automatically be uploaded and will not need formatting

**Comment by vikaspotluri123** [comment]
200x200. Best to focus on the face, less on the body.
