### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by vikaspotluri123** [thelinkscholars/thelinkscholars.github.io#40]
Every site should have a favicon, short for favorite icon. The role of the favicon is to serve as reference for your site for the end user. You can see favicons as icons next to the title of most modern browsers, and if you save a link to your desktop, your browser might set the icon as the favicon. Do you want to use your logo as the favicon (although favicons are generally square), or do you have one you can provide?

**Comment by thelinkscholars** [comment]
i'll consult my team on this one and respond with the best course of action

**Comment by thelinkscholars** [comment]
I have uploaded the favicon. It will be on the google drive named 40.favicon.png
Please also update the favicon at the bottom of the homepage with this new one.
