### ISSUE TITLE
(Home) cover photo optimal dimensions and resolution

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#41]
Please let me know what is the best dimensions for the cover photo, we are updating the cover.

**Comment by vikaspotluri123** [comment]
for parallax based cover photos, it is better to be  a little more than 500px in height, as the parallax itself is 400px high and needs some room for transformation.  For generic cover photos, the height should be 400px. If possible, it is best to have the width of all full-width images to be 1920px, but 1000px is the minimum.
