### ISSUE TITLE
(Home) NEW cover

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#42]

**Comment by thelinkscholars** [comment]
Yes, please replicate the text to the best of your ability.

**Comment by vikaspotluri123** [comment]
Do you know what happened to the image? I can no longer find it!

**Comment by thelinkscholars** [comment]
Hi Vikas, I have the image there let me know if you still cant find it

**Comment by vikaspotluri123** [comment]
I found the image!

**Comment by vikaspotluri123** [comment]
Is there a specific reason you want the logo to be in the hero? I got the replication to work, but it doesn't scale well. Given the logo is at the top, we can still overlay the main text as one row and it will be able to scale well. However, if you still really want the logo, I will put the image in drive.

**Comment by thelinkscholars** [comment]
So, I want the navbar to be part of the Hero and I don't want the logo to show at the top of the site when a visitor is on the homepage. This is because I want a very simple design language on the home page and nothing excessive. Check issue 47 for more context

**Comment by thelinkscholars** [comment]
all other pages would still remain the same layout withe the separated navbar at the top, just the hero on the home page would be blended with the navbar

**Comment by vikaspotluri123** [comment]
Will see what I can do

**Comment by vikaspotluri123** [comment]
I have made changes - thelinkscholars.github.io/index-new.html
Is this okay, or would you like the logo removed, nav centered and the image you uploaded used?

**Comment by thelinkscholars** [comment]
Can you make a version with the logo removed, nav centered and the image I uploaded I think it will look much cleaner and cooler

**Comment by vikaspotluri123** [comment]
It's available https://thelinkscholars.github.io/index-3.html

**Comment by thelinkscholars** [comment]
Yes! Let's keep that one as the new homepage. Also, try to clean up the homepage by getting rid of the lightning and the sponsors section and any empty space

**Comment by vikaspotluri123** [comment]
The light areas & lightening are placeholders for images. I have removed empty space and the sponsors sections as requested!

**Comment by thelinkscholars** [comment]
Great! Sounds good
