### ISSUE TITLE
UPDATE DESCRIPTIONS

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#45]
YAY MORE CONTENT :D

The doc is named the number of this issue as always, all changes have been highlighted, all cuts have been struck through.

**Comment by vikaspotluri123** [comment]
I lost track of what's done on this and what's not; Additionally, we changed structure of the site. Can you update the doc? Basically just highlight what needs to be changed and what needs to be added

**Comment by thelinkscholars** [comment]
Sure thing, i'll update the doc

**Comment by thelinkscholars** [comment]
The doc is updated, just the get involved page needs a little work and we'll be golden

**Comment by vikaspotluri123** [comment]
I've updated the get involved page. The phrase "Find our form below" seem out of place IMHO

**Comment by vikaspotluri123** [comment]
Done
