### ISSUE TITLE
(Contact) Background for page

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#51]

**Comment by vikaspotluri123** [comment]
This is done but might need some cropping

**Comment by thelinkscholars** [comment]
try to get the skyline in view, it's okay if the top of the sky is cut a little bit

**Comment by vikaspotluri123** [comment]
I can't do any cropping for a few weeks. However I can try to move the background.

**Comment by thelinkscholars** [comment]
yeah that works, that's what I meant

**Comment by thelinkscholars** [comment]
how come you can't crop for a few weeks? what do you mean?

**Comment by vikaspotluri123** [comment]
I don't have photoshop installed anymore. I can't do it for a while

**Comment by thelinkscholars** [comment]
ah I see, okay

**Comment by vikaspotluri123** [comment]
The transition is done. Please take a look and close the issue if no changes need to be made

**Comment by thelinkscholars** [comment]
The contact page is not live. I can't access it yet

**Comment by vikaspotluri123** [comment]
It will be live in the future. Available @ thelinkscholars.github.io/contact

**Comment by thelinkscholars** [comment]
Copy that.  You can cut the title that is in black and delete "Ishaat H." He is no longer part of the team

**Comment by thelinkscholars** [comment]
Please just update the phone numbers and we'll be all set with the contact page
