### ISSUE TITLE
Home Page Cleanup

### ISSUE THREAD

**Issue by vikaspotluri123** [thelinkscholars/thelinkscholars.github.io#52]
Try to clean up the homepage by getting rid of the lightning and the sponsors section and any empty space

**Comment by vikaspotluri123** [comment]
Looks like everything is done, just missing images.

**Comment by thelinkscholars** [comment]
Issue number 59 and 60 address this

**Comment by thelinkscholars** [comment]
I think we should put the upcoming events section under the (Contact) page and Lets move the services section to the (Services) page. So in summary, the home page should only be the main hero followed by the text, the secondary image of all the mentors followed by the mentee of the month section. I want to see what it would look like if we make the homepage as small and simple and concise as possible. I just want to test out the look, but we may revert back to the homepage format that is there currently if the other format doesn't look nice

**Comment by thelinkscholars** [comment]
Also, do you think it is possible to blend the bottom border, meaning like fade the bottom border, into the text that follows it and then blend/fade the top border of the second picture of all the mentors? I want it to look like one whole big section to see if it looks more elegant

**Comment by vikaspotluri123** [comment]
I have made changes to the page by removing sections. What do you mean by bottom border? What section are you talking about?

**Comment by thelinkscholars** [comment]
the border meaning like the bottom of the hero

**Comment by vikaspotluri123** [comment]
That would need to be done through image manipulation

**Comment by thelinkscholars** [comment]
okay, i'll see if I can do that

**Comment by vikaspotluri123** [comment]
Just kidding! I finally figured out how to do a gradient over the image; take a look!
On another note, I reduced the opacity of the header to 90% - what do you think of it?

**Comment by thelinkscholars** [comment]
LOOKING DOPE! Nice job man, thanks so much

**Comment by vikaspotluri123** [comment]
No problem! Is that what you're looking for in regards to the gradient? I've exaggerated it to highlight its existance

**Comment by thelinkscholars** [comment]
I mean it looks pretty good, but you can tone it down to your liking, I trust your judgement on what might look best!
