### ISSUE TITLE
(Home) Calendar

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#53]
is there a way for us to directly input dates, descriptions, etc into the calendar? or do I have to tell you on waffle to update these things anytime there's a new date or updated description etc?

**Comment by vikaspotluri123** [comment]
We're going to keep the dates temporary for now. There is a file in place that pulls the dates, which we will work on when the code is finished

**Comment by thelinkscholars** [comment]
Alright that's all I was wondering, thanks
