### ISSUE TITLE
Get Involved - Page Layout

### ISSUE THREAD

**Issue by vikaspotluri123** [thelinkscholars/thelinkscholars.github.io#54]
Since the get involved page has more sections and less content per section, I think it would be better to use a grid with a guidance text.

**Comment by thelinkscholars** [comment]
For now we can leave it. My team will be adding more content to that in due time, if they can't come up with enough content then we'll go ahead and do the grid

**Comment by vikaspotluri123** [comment]
Addressed in #68; closing
