### ISSUE TITLE
(Home) Button

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#57]
The "Find out how" hyperlink should be something like an elegant button of some sorts, i'll comment an example from a website

**Comment by vikaspotluri123** [comment]
Made changes. Something along the lines of what's there? I can change colors, size, etc!

**Comment by thelinkscholars** [comment]
Change color to Link Scholars theme color and take off the period

**Comment by thelinkscholars** [comment]
then you can move this to done
