### ISSUE TITLE
(Home) create section

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#60]
Please replace the bottom light area that has no content with a section that is called "Meet Our Mentee of the Month"

**Comment by vikaspotluri123** [comment]
The light area is a placeholder for an image. Would you like the section to be placed after it, or remove the image?

**Comment by thelinkscholars** [comment]
You'd like me to put an image there or you'd like to put an image there? I would prefer you to replace the image with the new mentee of the month section. P.S. i'll be going to bed now so just finish up whatever you have and i'll check it tomorrow. Thank you

**Comment by vikaspotluri123** [comment]
I'll delete the image
