### ISSUE TITLE
Changes on GitHub

### ISSUE THREAD

**Issue by vikaspotluri123** [thelinkscholars/thelinkscholars.github.io#63]
Please let me know if you make changes to the github repository. I need to pull those changes, or risk getting someone's work overwritten when I push.

**Comment by thelinkscholars** [comment]
sorry about that, I just updated the team headshots on the team pages

**Comment by vikaspotluri123** [comment]
It's perfectly fine! Just need a heads up so I can pull those changes before I make any!

**Comment by thelinkscholars** [comment]
alrighty, no problem. will do in the future!
