### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#65]
Update and Center the favicon at the bottom of the website and make that also redirect to the home page

**Comment by vikaspotluri123** [comment]
Just FYI for terminology, the favicon is the icon used in the tab and other ways that represent the site. Everywhere else it's the logo

**Comment by thelinkscholars** [comment]
ah okay

**Comment by vikaspotluri123** [comment]
Changes have been made. Is that good?

**Comment by vikaspotluri123** [comment]
Can this be closed?

**Comment by thelinkscholars** [comment]
yes, but please update the logo with our new logo, I know it's minor but we're officially going to be branded as "The Link Scholars" instead of just "Link Scholars"

**Comment by thelinkscholars** [comment]
you can just use file number 40.favicon.jpg on the drive to replace the old one

**Comment by vikaspotluri123** [comment]
I think this has already been done. Please verify and let me know.
