### ISSUE TITLE
Hero scaling

### ISSUE THREAD

**Issue by vikaspotluri123** [thelinkscholars/thelinkscholars.github.io#66]
Hero image doesn't scale well - see mobile device

**Comment by thelinkscholars** [comment]
is it possible to do a mobile version of the hero? like I could provide a smaller scaled version but I'm not sure if mobile site can be separated from original full desktop version

**Comment by vikaspotluri123** [comment]
Yep I can separate them!

**Comment by thelinkscholars** [comment]
I'll make a mobile version and upload it to the drive soon

**Comment by thelinkscholars** [comment]
I've uploaded the new mobile version. Do you think you can do a better job at making that image or do you think it looks good enough? It's in the drive as 66.mobile.site.png

**Comment by vikaspotluri123** [comment]
I still don't have photoshop setup, and I'm not that good at it in the first place. There is some minor scaling that needs to be done.

**Comment by thelinkscholars** [comment]
alright hold on

**Comment by vikaspotluri123** [comment]
Changes have been pushed

**Comment by thelinkscholars** [comment]
okay, I'll wait and see how this picture turned out
