### ISSUE TITLE
(Services) rearrange the services content

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#70]
make the content vertically linear and get rid of the empty content. Also add a gallery section to the top of the page, I'll make a folder in drive to get the pictures from, do you prefer specific size so I can convert it before I upload it to the folder to make your task easier?

**Comment by thelinkscholars** [comment]
Also remove the secondary blue navbar on this page, I don't think we need it

**Comment by vikaspotluri123** [comment]
What type of gallery do you want? A carousel (can see multiple images at once and scroll), or a slider (one image at a time w/ progress dots at the bottom)?

**Comment by vikaspotluri123** [comment]
I think I've done the rearranging you want

**Comment by thelinkscholars** [comment]
Slider gallery is appropriate for this content

**Comment by vikaspotluri123** [comment]
Are you thinking something like the team page?

**Comment by thelinkscholars** [comment]
no, traditional slideshow style
