### ISSUE TITLE
(Services) <Gallery> fix

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#76]
Do you think it is possible to push the gallery down a bit more? all the images have their top sections cut so some of the content is missed out on. Let me know what you can do and what I can do to help alleviate the issue

**Comment by thelinkscholars** [comment]
also can you add arrow buttons on each side so it's easier to go to the next picture or go back, the arrows should only appear when your cursor hovers over them but otherwise not be there

**Comment by vikaspotluri123** [comment]
The cutoff is due to the squareness of the original photos. I added some top padding to highlight the issue. The height of the slider can be modified; as of now it's 400px

**Comment by thelinkscholars** [comment]
ah, I see. So is there something I can do so that we can see the entirety of the photos?

**Comment by vikaspotluri123** [comment]
The height would have to be increased dramatically, or you can crop the picture

**Comment by vikaspotluri123** [comment]
The buttons under the gallery serve as the option to navigate, instead of arrows. Do you want to keep that navigation still?

**Comment by thelinkscholars** [comment]
yes, keep the buttons but also add arrows, although I've realized that on mobile version you can swipe to change, so just the desktop version can have the arrows

**Comment by thelinkscholars** [comment]
how should I crop the pictures? would you like me to make them into squares? rectangles? which works better?

**Comment by vikaspotluri123** [comment]
For generic photos, the height should be 400px. If possible, it is best to have the width of all full-width images to be 1920px, but 1000px is the minimum.

**Comment by vikaspotluri123** [comment]
added arrows

**Comment by thelinkscholars** [comment]
okay, I like the gallery now it looks good
