### ISSUE TITLE
(Blog) Make pictures more visible

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#86]
If there's any issues with scaling, let me know and i'll try to upload better scaled pictures so it's easier to upload. We need the pictures in the blog to be fully visible that's why

**Comment by vikaspotluri123** [comment]
Is this for the post-specific page, or the blog page?

**Comment by thelinkscholars** [comment]
what is the post specific page? I was referring to each blog post on the blog page

**Comment by vikaspotluri123** [comment]
The blog page serves a summary / excerpt of the post. Each post will link to their specific page in the future.  The images at the top of the older posts are there to test the featured image functionality. They will be removed in the future, unless there is a featured image. Do you want a generic image to be placed for posts that don't have a featured image?

**Comment by thelinkscholars** [comment]
okay I see, so yeah the posts will have a featured image and a generic image is good if there is no image provided

**Comment by vikaspotluri123** [comment]
Can you provide the image? If not, what type of image are you looking for? You can upload the file as issue 86!

**Comment by thelinkscholars** [comment]
if you mean one image for the blog page then I don't have a picture in mind for that. Each post will have its own featured image but you can just keep the layout and format as it is, it doesn't need to be changed anymore

**Comment by vikaspotluri123** [comment]
Okay. What about posts where you don't have a chance to create a featured image or there isn't one? Do you want a generic image to be there?

**Comment by thelinkscholars** [comment]
You can just leave it. No need for an image at all in that case
