### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by vikaspotluri123** [thelinkscholars/thelinkscholars.github.io#89]
You might want to add more content for the footer.

**Comment by thelinkscholars** [comment]
what do you have in mind to add? I don't really know what should go there

**Comment by vikaspotluri123** [comment]
Copyright, Sitemap, Privacy Policy, Contact (maybe not?), Address / contact info,  press page,  search?,  Mission / values, etc. I don't really have anything specific in mind, but it just feels like it's missing something

**Comment by thelinkscholars** [comment]
Yeah we could use the things you mention, whatever you feel is appropriate but I understand what you mean by it feeling sort of empty

**Comment by thelinkscholars** [comment]
no need for address or press page but lets do Copyright, Sitemap, Privacy Policy, Contact and then The Link Scholars - 2017 All rights reserved

**Comment by vikaspotluri123** [comment]
Given the tiny amount of content, I'm thinking of making the footer tiny. Can the search be moved to the header? Unless clicked, it will be a magnifying glass. This would also entail removing the logo from the footer and possibly moving the social icons.

**Comment by thelinkscholars** [comment]
yes to everything you just said :)

**Comment by vikaspotluri123** [comment]
Do you see a need for search? Especially with a sitemap?

**Comment by vikaspotluri123** [comment]
Everything else is done!

**Comment by thelinkscholars** [comment]
We don't need search if we have a sitemap

**Comment by thelinkscholars** [comment]
Hi, The "hexr" hyperlink is a little too low, do you mind having it on the same level as the "2017 link scholars" text?

**Comment by vikaspotluri123** [comment]
It should be on the same level to start with. Can you give me the specs you're using? (Browser, computer, etc.)

**Comment by thelinkscholars** [comment]
Google Chrome - Latest version, Windows 10 Laptop, Intel Core i5 6200U, 8GB RAM

**Comment by vikaspotluri123** [comment]
Is it fixed now? I'm not sure if I'm missing something
![image](https://cloud.githubusercontent.com/assets/4383564/23837616/dedb72e4-0758-11e7-9f56-33c088d8cc91.png)

**Comment by thelinkscholars** [comment]
Yes, it is fixed now
