### ISSUE TITLE
Sliders

### ISSUE THREAD

**Issue by vikaspotluri123** [thelinkscholars/thelinkscholars.github.io#90]
Not working on mobile

**Comment by vikaspotluri123** [comment]
@thelinkscholars  It looks like the problem is only the large arrows. Is it okay to remove them on mobile only?

**Comment by thelinkscholars** [comment]
yes!

**Comment by thelinkscholars** [comment]
it can be swipe based navigation

**Comment by vikaspotluri123** [comment]
@thelinkscholars does your swipe navigation lag a lot on the services page? I'm not sure if it's me or something is wrong with the slider, as I've commented most of the blocking code out and it still lags.

**Comment by thelinkscholars** [comment]
The swipe navigation isn't having any problems on my end :/

**Comment by vikaspotluri123** [comment]
Just to confirm, that's on mobile? If you're not having problems I'm not going to worry about it!

**Comment by thelinkscholars** [comment]
Yes that's correct, also, sorry about the extremely late response. I had originally turned off notifications and forgot to turn them back on, going to do that now :)
