### ISSUE TITLE
(Home) Mentee of the Month

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#91]
check the google drive for image and description

**Comment by thelinkscholars** [comment]
Name is Nasima Akther. Check the Blog doc for the blog post and don't enter the whole interview on the home page, just add a "Read More About Me!" button under her picture that leads to the blog post

**Comment by vikaspotluri123** [comment]
Fixed. Sorry for the delay, editor had save issues!

**Comment by thelinkscholars** [comment]
No Problem! Please correct the name though, it's Nasima with an N not Masima :)
