### ISSUE TITLE
Need Privacy Policy

### ISSUE THREAD

**Issue by vikaspotluri123** [thelinkscholars/thelinkscholars.github.io#93]

**Comment by thelinkscholars** [comment]
I'll draft up something with my team

**Comment by thelinkscholars** [comment]
So what kind of information would our site collect from our users?

**Comment by vikaspotluri123** [comment]
Google Analytics and forms is all. Unless you integrate with any other third party services

Google Analytics is a web analysis service provided by Google. Google utilizes the data collected to track and examine the use of www.example.com, to prepare reports on its activities and share them with other Google services.
Google may use the data collected to contextualize and personalize the ads of its own advertising network.

Personal data collected: Cookie and Usage Data. Place of processing: USA. Find Google's privacy policy [here](http://www.google.com/intl/en/policies/privacy/).

**Comment by thelinkscholars** [comment]
Privacy policy has been updated! if you have any edits you can make them but otherwise I've made one and named it under the number of this issue

**Comment by thelinkscholars** [comment]
hasn't shown up on the website yet

**Comment by vikaspotluri123** [comment]
Typo! All fixed
