### ISSUE TITLE
(Get Involved)

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#94]
When I go on this page and try to navigate to a different page a prompt shows up asking me if I would like to leave this page when I haven't submitted any info or filled anything out, can you take a look at this?

**Comment by vikaspotluri123** [comment]
Does this happen after you open a Google Form?

**Comment by vikaspotluri123** [comment]
Based on e8d0076  it looks like Google Forms was the culprit. I'm guessing until Google fixes the bug (if it is a bug), the forms will open in a new tab as they are right now.

**Comment by thelinkscholars** [comment]
That's okay, we prefer the Link to redirect to a google form in a new tab
