### ISSUE TITLE
<Enhancement> (Team)

### ISSUE THREAD

**Issue by thelinkscholars** [thelinkscholars/thelinkscholars.github.io#97]
I want to experiment with the layout and design of this page. Lets Center the headshot with the name under it with the description under that

**Comment by vikaspotluri123** [comment]
This has been done!

**Comment by thelinkscholars** [comment]
This hasnt shown up on the site, maybe you haven't pushed the changes?

**Comment by vikaspotluri123** [comment]
Oh, it's a new [https://thelinkscholars.github.io/team/new.html](url)

**Comment by thelinkscholars** [comment]
sorry I missed this, i'll let you know what my team thinks of this layout, thanks

**Comment by thelinkscholars** [comment]
We prefer the center style!
